# Generated by Django 5.0 on 2023-12-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=100),
        ),
    ]
