# Generated by Django 5.0 on 2023-12-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_alter_user_username"),
    ]

    operations = []
