# Generated by Django 5.0 on 2023-12-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0003_auto_20231219_0700"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="Type Your biography", max_length=100),
        ),
    ]
